# Generated by Django 6.1 on 2026-09-04 01:09

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_gender_material_stone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.stone'),
        ),
    ]
